version: '3.8'

services:
  server:
    env_file: ./server/.env
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: my_server
    tty: true
    stdin_open: true
    volumes:
      - socket-vol:/tmp
      - ./db:/app/db
    networks:
      - appnet

  client:
    env_file: ./client/.env
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: my_client
    tty: true
    stdin_open: true
    depends_on:
      - server
    volumes:
      - socket-vol:/tmp
    networks:
      - appnet

volumes:
  socket-vol:

networks:
  appnet:
    driver: bridge
